- akita/__tests__/query-entity.spec.ts
- akita/src/api/query-entity.ts
- package-lock.json
when active is null we don't need to throw, we return undefined
```
[ x ] Bugfix
[ ] Feature
```
Don't throw if active doesn't exist. 
```
[ ] Yes
[ ] No
```
> fix(query): don't throw when active is null

- akita/src/api/entity-store.ts
- package-lock.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(entity-store): allow zero as id

- akita/__tests__/crud.spec.ts
- akita/src/api/entity-store.ts
- akita/src/api/types.ts
- akita/src/internal/crud.ts
set now can accept the complete state object
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(crud): set now can accept the complete state object

- akita/src/api/arrays.ts
- akita/src/api/entity-store.ts
- akita/src/api/query-entity.ts
- akita/src/api/query.ts
- akita/src/api/store.ts
- akita/src/api/transaction.ts
- akita/src/api/types.ts
- akita/src/api/worker.ts
- package-lock.json
Add @example for each jsdoc code block.
This improves semantics and therefore IDE and other tooling support.
I was checking out your project because I'm really uncomfortable with NGRX, thought I could write 5 letters here and there when reading the code haha :grinning: 
I've yet to test it out but keep up the good work anyway !
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(api): add @example tag to jsdoc

- .all-contributorsrc
- README.md
- akita/__tests__/dirty-check.spec.ts
- akita/src/plugins/dirty-check/dirty-check-plugin.ts
- akita/src/plugins/dirty-check/entity-dirty-check-plugin.ts
- akita/src/plugins/entity-collection-plugin.ts
- package-lock.json
```
[ ] Bugfix
[x] Feature
```
EntityDirtyCheckPlugin now supports checking for at least one dirty entity in a collection.
```
[ ] Yes
[x] No
```
> feat(dirty-check-plugin): add isSomeDirty to EntityDirtyCheckPlugin

- akita/src/plugins/dirty-check/entity-dirty-check-plugin.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(dirty-check-plugin): add type remove unnecessary code

- akita/__tests__/dirty-check.spec.ts
- akita/src/plugins/dirty-check/dirty-check-plugin.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(dirty-check-plugin): add public api for isDirty() and hasHead()

- akita/src/api/entity-store.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> (refact): Use already computed coerceArray()

- akita/__tests__/entity-store.spec.ts
- akita/src/api/entity-store.ts
- akita/src/internal/crud.ts
- akita/src/internal/global-state.ts
- akita/src/internal/utils.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(active): reset the active when the entity does not exist

- akita/src/plugins/state-history/entity-state-history-plugin.ts
- package-lock.json
```
[ ] Bugfix
[X] Feature
```
No api for ignoreNext form entityStateHistory
```
[ ] Yes
[X] No
```
> feat(history plugin): add public api for ignoreNext

- akita/src/internal/deep-freeze.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #94
```
[ ] Yes
[x] No
```
> fix(store): use IE11 strict mode compatible deep-freeze

- akita/src/internal/crud.ts
- package-lock.json
```
[X] Bugfix
[ ] Feature
```
Update use's the old state constructor instead of the new state constructor.
Update use's the new state constructor.
> fix(crud-update): use new state constructor instead of the old state

- CONTRIBUTING.md
- README.md
Fix typographical errors in Readme and Contributing markdown files
```
[ ] Bugfix
[ ] Feature
[x] Documentation content changes
```
> docs: fix small typos

- akita/src/index.ts
```
[x] Bugfix
[ ] Feature
```
Based on the document, these two transaction operators should be exported, but the code doesn't export these two operator.
Export theses two operators.
```
[ ] Yes
[x] No
```
> fix(transaction): expose transaction operator

- akita/__tests__/pagination.spec.ts
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: add test
```
No test for "take current page from response"
Add test for "take current page from response"
```
[ ] Yes
[x] No
```
> test(paginator): add test for "take current page from response"

- akita/__tests__/stateHistory.spec.ts
- akita/src/plugins/stateHistory/stateHistoryPlugin.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: [227](https://github.com/datorama/akita/issues/227)
The state history can now be cleared in custom ways, e.g. only the future.
```
[ ] Yes
[x] No
```
> feat(history-plugin): allow custom clear function

- akita/__tests__/arrayAdd.spec.ts
- akita/src/arrayAdd.ts
```
[ ] Bugfix
[x] Feature
```
`arrayAdd` fails when there is no empty array.
`arrayAdd` upserts: If the field is null or undefined, create an empty array before concat.
```
[ ] Yes
[x] No
```
> feat(array-add): upserts

- akita/__tests__/arrayUpsert.spec.ts
- akita/src/arrayAdd.ts
- akita/src/arrayRemove.ts
- akita/src/arrayUpdate.ts
- akita/src/arrayUpsert.ts
- angular/playground/package-lock.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> Array Upsert

- akita/src/filterNil.ts
- akita/src/types.ts
```
[ ] Bugfix
[ ] Feature
```
Issue Number: datorama#157
```
[ ] Yes
[ ] No
```
> Xealot filter nil

- akita/src/plugins/dirtyCheck/dirtyCheckPlugin.ts
Closes 268
_this change not required test_
_not required docs update_
```
[x] Bugfix
[ ] Feature
```
Issue Number: #268 
working code completion
```
[ ] Yes
[x] No
```
When filling out this template i saw prettier changes, revert this or leave it?
> fix(dirty-check-plugin): added missing generic type in DirtyCheckParams

- akita/__tests__/runStoreAction.spec.ts
- akita/src/runStoreAction.ts
```
[ ] Bugfix
[X] Feature
```
`runStoreAction` cannot perform `upsert`
`runStoreAction` can perform `upsert`
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature …
```
> Add support for Upsert in runStoreAction

- akita/src/runStoreAction.ts
```
[X] Bugfix
[ ] Feature
```
When using upsert with runActionStore, the update function was also triggered
It works as expected
```
[ ] Yes
[X] No
```
> fix(run-store-action): add return in switch case

- akita/src/devtools.ts
- examples/angular-ecommerce/src/app/app.module.ts
Sorting  stores alphabetically in Redux devtools, closes #325
> feat(devtools): add ability to sort the displayed store in devtools

- akita/src/transaction.ts
Updated typings
```
[x] Bugfix
[ ] Feature
```
While `withTransaction` is called with a generic parameter. The generic type is not used and the parameter passed into `withTransaction` is implizit `any`.
Parameter passed into `withTransaction` is now equal the generic type provided when calling `withTransaction`
```
[ ] Yes
[x] No
```
> fix(withTransaction): Fixed typing

- akita/__tests__/stateHistory.spec.ts
- akita/src/plugins/stateHistory/stateHistoryPlugin.ts
- added hasPast$ and hasFuture$
- added test spec for observability
```
[ ] Bugfix
[x] Feature
```
The current stateHistoryPlugin does not provide a mechanism for knowing when there is a past or future that can be jumped / undo / redo.
There are now two observable properties that allow for observing changes in the hasPast or hasFuture of the state plugin.
```
[ ] Yes
[x] No
```
> feat: add observable past & future for history

- akita/__tests__/arrayFind.spec.ts
- akita/src/arrayFind.ts
change id param type from number to ID
Resolves #349
Please enter the commit message for your changes. Lines starting
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix: change arrayFind id param type

- cli/README.md
- cli/plopfile.js
- cli/templates/angular/entity-store.tpl
- cli/templates/js/entity-store.tpl
- cli/templates/ts/entity-store.tpl
```
[ ] Bugfix
[x] Feature
```
Can customize the idKey name in the package.json.
```
[ ] Yes
[x] No
```
> feat(cli): customize the idKey

- akita/__tests__/queryEntity.spec.ts
- akita/src/queryEntity.ts
```
[x] Bugfix
[ ] Feature
```
when id is provided to `hasActive` it will return true if the active id differs from the provided one
will return false if ids are not equal
```
[ ] Yes
[x] No
```
> fix(has-active): fix condition when id provided

- libs/akita/src/lib/index.ts
- libs/akita/src/lib/persistState.ts
PR Checklist
```
[ ] Bugfix
[x] Feature
```
exposing the return type allows it to be registered as a provider in Angular
```
[ ] Yes
[x] No
```
> feat(persist-state): expose `persistState` return type

- .github/PULL_REQUEST_TEMPLATE.md
> docs: fix task lists in PULL_REQUEST_TEMPLATE.md

- .gitignore
- tools/akita-cli/templates/angular/index.tpl
- tools/akita-cli/templates/ts/index.tpl
> improvement(akita-cli): stop exporting createInitialState from index.ts

- libs/akita/src/__tests__/env.spec.ts
- libs/akita/src/lib/env.ts
> fix(env): don't access window outside of browser

- docs/docs/enhancers/devtools.mdx
Currently links to 404 page
links to the presumably intended https://addons.mozilla.org/en-US/firefox/addon/reduxdevtools/
> docs: updated firefox redux devtool link

- README.md
> docs: update akita-cli repository link

- BREAKING_CHANGES.md
- libs/akita/src/lib/queryEntity.ts
> fix(query-entity): selection of a single entity can be undefined

- docs/docs/store.mdx
Destroyes -> Destroys
`Destroyes the store:`
`Destroys the store:`
> docs: correct typo in store.mdx

- docs/docs/enhancers/persist-state.mdx
- libs/akita/src/__tests__/persistStateSelect.spec.ts
- libs/akita/src/lib/index.ts
- libs/akita/src/lib/persistState.ts
closes #373
Issue Number: #373
> feat(persist-state): add ability to select store data to persist

- docs/docs/additional/events.mdx
- libs/akita/src/__tests__/runStoreAction.spec.ts
- libs/akita/src/lib/runStoreAction.ts
> fix(run-store-action): add untyped store support

- libs/akita/src/lib/index.ts
fix #472
Issue Number: #472
Global export of `StoreAction` and `EntityStoreAction`.
> fix(run-store-action): add package exports for store actions

- docs/docs/angular/schematics.mdx
- libs/akita-schematics/src/ng-g/feature/schema.json
- libs/akita-schematics/src/ng-g/utils/parse-name.ts
Feature schematic doesn't have `flat` flag.
Issue Number: #393 
Feature schematic has `flat` flag.
> feat(schematics): implement 'flat' flag for feature

- docs/docs/entities/active.mdx
no documentation for store options
Issue Number: #477 
added documentation for schematics store options
> Add new schematics tips to documentation #477

- docs/docs/angular/schematics.mdx
no documentation for store options
Issue Number: #477
added documentation for schematics store options
> Update the feature and store docs for new option #477

- docs/docs/additional/operators.mdx
> docs: correct spelling of Entity

- docs/docs/angular/entity-service.mdx
> docs: Fix typo in entity-service.mdx

- apps/react-akita-app/README.md
Incorrect app name in nx serve command.
`nx serve akita-react-app`does not work
When I type `nx serv react-akita-app`, it works well. So I modified the docs
I don't know if the expression was delivered correctly, not by English speakers.
But if you look at the code, it's easy to understand.
> docs: update nx serve command

- docs/docs/additional/cache.mdx
Tap operator syntax error due to parenthesis closed after parameter and productsStore should be called with 'this'
Fix above syntax errors in cache example code
> docs: Fix cache example code

- docs/docs/enhancers/snapshot.mdx
> Fix 'setStoresSnapshot with lazy option' doc example

- docs/docs/angular/local-state.mdx
Fix factory sample in local-state.mdx
> chore(docs) fix local-state.mdx

- libs/akita/src/__tests__/pagination.spec.ts
- libs/akita/src/lib/plugins/paginator/paginatorPlugin.ts
> fix(paginator): update entities on store

- docs/docs/entities/entity-store.mdx
I'm sweeping over all documentation, and might introduce more small changes to different files, so the PR can be on hold for a while. Of course the PR title will be updated to accommodate the different changes.
> docs(akita): update detail about `EntityStore#upsert`

- docs/docs/transactions.mdx
> docs: fix the typo in transactions.mdx

- docs/docs/entities/entity-store.mdx
> docs: add section regarding nested entity id (using akitaPreAddEntity)

- docs/docusaurus.config.js
- docs/package.json
> Upgrade docusaurus version

- tools/akita-cli/templates/ts/model.tpl
When creating a model with schematics, the `createModel` function ignores the received params when returning the new object
`createModel` function returns the created object with the sent params.
> fix(): add params to created object

- libs/akita-schematics/src/ng-g/feature/schema.json
Issue Number: #551 
Now pages are exists
> chore(schematics): update links in generate feature dialog

- libs/akita-schematics/src/ng-add/index.ts
Issue Number: 547
Updates ng add schematic to use latest production version of akita-ng-fire dependency.
Apologize for the initial non-compliant commit message. Only realized it after the commit was pushed.
> Updated akita-ng-fire dependency to latest version (#547)

- libs/akita/src/lib/persistState.ts
clear function is exposed when creating persistState
Issue Number: #532 
mark clear function as deprecated until it will be removed in the next major release
> chore(persist-state): deprecate clear function (#532)

- docs/docs/entities/active.mdx
> docs: fix an import bug in active example

- libs/akita/src/__tests__/stateHistory.spec.ts
- libs/akita/src/lib/setValueByString.ts
- [x ] The commit message follows our guidelines: https://github.com/datorama/akita/blob/master/CONTRIBUTING.md#commit
- [x ] Tests for the changes have been added (for bug fixes / features)
- [x ] Bugfix
https://github.com/datorama/akita/issues/557
Issue Number: 557
As expected
- [x ] No
> fix(lib): restored array state is not changed to an object literal

- docs/docs/enhancers/persist-state.mdx
- libs/akita/src/lib/persistState.ts
✅ Closes: #566
Issue Number: #566
> feat: 🎸 provide initial state to preStoreUpdate hook

- docs/docs/angular/tests.mdx
Issue Number: https://github.com/datorama/akita/issues/568
> docs: fix angular query unit test (fix #568)

- docs/package.json
`yarn build` offers `npm run serve`, but `serve` isn't wired in yet
`Success! Generated static files in akita. Use `npm run serve` to test your build locally`
`yarn serve` and `yarn clear` passes through to docusaurus
https://v2.docusaurus.io/docs/cli/#docusaurus-serve
https://v2.docusaurus.io/docs/cli/#docusaurus-clear
> chore(docs): add serve and clear cmds

- docs/package.json
- docs/yarn.lock
Package update
docusaurus 2.0.0-65
react 16.8
No behavioral changes
- docusaurus 2.0.0-70 ([changelog](https://github.com/facebook/docusaurus/blob/v2.0.0-alpha.70/CHANGELOG-2.x.md))
- react 17.01 ([changelog](https://github.com/facebook/react/blob/eaaf4cb/CHANGELOG.md))
changelogs:
- react: https://github.com/facebook/react/blob/eaaf4cb/CHANGELOG.md
- docusaurus: https://github.com/facebook/docusaurus/blob/v2.0.0-alpha.70/CHANGELOG-2.x.md
> chore(docs): update dependencies

- docs/docs/additional/array.mdx
Example is updating non-existent property on state
> docs: fix array util example

- libs/akita-ng-effects/package.json
- package.json
Collection json has been removed from akita ng effects
> docs: Fix link (#586)

- docs/docs/angular/effects.mdx
The documentation of the property `dispatch` of `EffectOptions` was missing in the official documentation confusing a state management newbie.
The documentation of the property `dispatch` of of `EffectOptions` is now in the official documentation.
> docs: update docs of dispatch property of EffectOptions

- libs/akita-ng-effects/src/lib/types.ts
Issue Number: #612 
Updating comments of dispatch property of EffectOptions
> docs(code): update comments of dispatch property of EffectOptions

- libs/akita-schematics/src/ng-g/firebase-entity-service/files/__name@dasherize__.service.spec.ts
- libs/akita-schematics/src/ng-g/http-entity-service/files/__name@dasherize__.service.spec.ts
- libs/akita-schematics/src/ng-g/service/files/__name@dasherize__.service.spec.ts
> fix(schematics): use TestBed.inject instead of TestBed.get (#611)

- docs/docs/enhancers/persist-state.mdx
There is no documentation on how to persist store to separate branch in localStorage.
Documentation with examples how to persist store to separate branch in localStorage using angular multi provider.
> docs(persist-state): separate branch in storage

- docs/docs/ui.mdx
> Fix(docs): Add `=` on `export type` declaration

- docs/docs/query.mdx
> docs(query): add SessionStore import

- docs/docs/angular/local-state.mdx
I've added Injectable decorator to CounterStore
> I've added Injectable decorator to CounterStore

- .all-contributorsrc
- README.md
> docs: add @everduin94 as a contributor

- libs/akita/package.json
- package.json
- yarn.lock
> fix: update dependency schematics-utilities

- apps/angular-store-app/src/app/auth/auth.module.ts
- apps/angular-store-app/src/app/auth/state/auth.effects.ts
- apps/angular-store-app/src/app/cart/state/cart.effects.ts
- apps/angular-store-app/src/app/contacts/state/contact.effects.ts
- apps/angular-store-app/src/app/movies/movies.module.ts
- apps/angular-store-app/src/app/movies/state/movie.effects.ts
- apps/angular-store-app/src/app/posts/posts.module.ts
- apps/angular-store-app/src/app/posts/state/post.effects.ts
- apps/angular-store-app/src/app/products/products.module.ts
- apps/angular-store-app/src/app/products/state/products.effects.ts
- libs/akita-ng-effects/src/lib/actions.ts
- libs/akita-ng-effects/src/lib/akita-ng-effects.module.ts
- libs/akita-ng-effects/src/lib/effect-feature.module.ts
- libs/akita-ng-effects/src/lib/module-manager.service.ts
> fix(akita-ng-effects): fix registration of multiple for features

- CHANGELOG.md
> docs(changelog): fix incorrect dates in the changelog

- docs/docs/angular/schematics.mdx
Found some grammar issues on this page so I decided to fix them :)
> docs(angular-schematics): spelling and grammar improvements

- libs/akita/src/lib/plugins/stateHistory/entityStateHistoryPlugin.ts
- [x ] The commit message follows our guidelines: https://github.com/datorama/akita/blob/master/CONTRIBUTING.md#commit
- [x ] Feature
Issue Number: #719 
- [x ] No
> feat(entity-state-history-plugin): allow custom clear function (#719)

- libs/akita-schematics/src/ng-g/utils/ast-utils.ts
> refactor(schematics): fix typo in ast-utils.ts

- .github/workflows/deploy-sample-app.yml
```
[ ] Bugfix
[ ] Feature
[x] CI related changes
[x] Documentation content changes
```
Issue Number: salesforce/akita#1052
This PR enables CI to build and deploy `ng-playground` to akita.surge.sh
```
[ ] Yes
[x] No
```
Requires specifying `surge_login` and `surge_token` env variables (can be obtained by running `surge token`)
> chore(general): configure sample-app deployment
