akita/__tests__/dirty-check.spec.ts, akita/src/plugins/dirty-check/entity-dirty-check-plugin.ts
Add signature for is dirty to be able to return boolean.
Add public API for hasHead() 
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(entity-dirty-check-plugin): change signature of isDirty

akita/src/api/arrays.ts
```
[x] Bugfix
```
Currently `push`, `unshift`, `splice` and `toggle` use any as input.  
I don't know if it is intended behavior but it seems wrong to me and makes for bad IDE integration.
They now take either `T` or  `...T[]` as input type.
```
[x] Yes
[ ] No
```
For users providing non `T` or `T[]` types, the code won't compile anymore which is a actually a good thing.
If this is indeed not intended behavior, I strongly recommend setting `noImplicitAny` to true, it would've maybe help catch this error at compile time.
=> (fix): Update typings for immutable array helpers

akita/__tests__/crud.spec.ts, akita/__tests__/entity-store.spec.ts, akita/src/api/entity-store.ts, akita/src/internal/crud.ts
- [O] Docs have been added / updated (for bug fixes / features)
```
[X] Bugfix
[X] Feature
[X] Code style update (formatting, local variables)
```
Currently, there was no way to easily update/remove entities based on anything other than IDs
Issue Number: #46 
Introduced a new overload for both, the `update` and `remove` methods that accept a predicate.
Also fixes a bug described in the comments of #46
Notice the changes in the imports. My IDE sorts them alphabetically. That's all there's to it.
```
[ ] Yes
[X] No
```
=> feat: EntityStore.update/remove should accept predicate for ids

akita/__tests__/dirty-check.spec.ts, akita/src/plugins/dirty-check/entity-dirty-check-plugin.ts
```
[x] Bugfix
[ ] Feature
```
isSomeDirty is only available as an observable<boolean>.
isSomeDirty is now available as boolean as well
=> fix(entity-dirty-check): Add boolean isSomeDirty

akita/__tests__/dirty-check.spec.ts, akita/__tests__/setup.ts, akita/src/plugins/dirty-check/dirty-check-plugin.ts, akita/src/plugins/dirty-check/entity-dirty-check-plugin.ts, akita/src/plugins/entity-collection-plugin.ts, akita/src/plugins/plugin.ts, playground/src/app/nav/nav.component.ts, playground/src/app/widgets/state/widget.model.ts, playground/src/app/widgets/state/widgets.service.ts, playground/src/app/widgets/state/widgets.store.ts, playground/src/app/widgets/widgets.component.html, playground/src/app/widgets/widgets.component.ts
```
[ ] Bugfix
[x] Feature
```
DirtyCheckPlugin tracks the entire store only
You can pass which property of the store state you want to track
```
[ ] Yes
[x] No
```
=> feat(dirty-check): add support for key based check

akita/src/api/query.ts
- [ X] The commit message follows our guidelines: https://github.com/datorama/akita/blob/master/CONTRIBUTING.md#commit
- [ X] Tests for the changes have been added (for bug fixes / features)
```
[ X] Bugfix
[ ] Feature
```
The return type on `query.select` when passing a predicate is no longer an `Observable` and Typescript see it as `any`.
Issue Number: 75
https://github.com/datorama/akita/issues/75
The return type is specified as `Observable<R>` where `R` is the …
=> fix(query): select method signature missing Observable return type

akita/__tests__/entity-store.spec.ts, akita/src/api/entity-store.ts, akita/src/api/types.ts, akita/src/internal/crud.ts, playground/package-lock.json
I can't find your doc. I can make an update if you allow me.
```
[ ] Bugfix
[x] Feature
```
`store.add(new Todo({ id: 1 }));` cannot prepend
`store.add(new Todo({ id: 0 }),{prepend:true});` can prepend to the list
```
[ ] Yes
[x] No
```
=> feat(entity store): allow prepend option when adding

akita/__tests__/reset-stores.spec.ts, akita/src/api/store-utils.ts, akita/src/api/store.ts, playground/src/app/nav/nav.component.ts
```
[ ] Bugfix
[X] Feature
```
Issue Number: 104
resetStores function is now available via store-utils, to allow resetting all stores to their initialState as configured by the user.
the function have an excluded property as an option, an array of strings that will exclude the specific store names from the reset process.
```
[ ] Yes
[X] No
```
=> resetStores util function

akita/__tests__/query-entity.spec.ts, akita/src/api/query-entity.ts
Send current index in custom filter function to deal with it filter.
See: https://github.com/datorama/akita/issues/117
- [ x] The commit message follows our guidelines: https://github.com/datorama/akita/blob/master/CONTRIBUTING.md#commit
- [x ] Tests for the changes have been added (for bug fixes / features)
- [x ] Docs have been added / updated (for bug fixes / features)
```
[ ] Bugfix
[x ] Feature
```
The filter function filterBy provide only the current Element. …
=> feat(query-entity): provide index in filter function

README.md
Fix the URL of the link pointing to the blog-posts
```
[ ] Bugfix
[ ] Feature
[x] Documentation content changes
```
Current link to the blog-posts points to a page that does not exist
The link to the blog-posts now correctly points to the blog-posts page on the gitbook
```
[ ] Yes
[x] No
```
=> docs(readme): fix link pointing to blog-posts

akita/src/root.ts
Hey folks, 
I absolutely love Akita and I think it's awesome and very delightful to use :)
```
[x] Bugfix
[ ] Feature
```
When using Akita inside [NativeScript](https://www.nativescript.org/) not all functionalities work. The reason is the `isNotBrowser` check. For example [`persistState`](https://github.com/datorama/akita/blob/master/akita/src/persistState.ts#L56) is guarded with this check.
Using Akita in NativeScript apps should be similar to using it browsers. I …
=> fix: add platform check for NativeScript

akita/__tests__/deepFreeze.spec.ts, akita/src/store.ts, akita/src/storeConfig.ts
Adds deepFreezeFunction in StoreConfigOptions and unit tests for feature
Can use custom deepFreeze for complex objects in store
Resolves #124
- [X ] The commit message follows our guidelines: https://github.com/datorama/akita/blob/master/CONTRIBUTING.md#commit
- [X ] Tests for the changes have been added (for bug fixes / features)
```
[ ] Bugfix
[X ] Feature
```
Objects in store are frozen with deepFreeze on _setState. Complex states or entities might break when frozen …
=> feat(store,storeconfig): config for deepFreeze function

akita/__tests__/pagination.spec.ts, akita/src/plugins/paginator/paginatorPlugin.ts
This changes are based on a change previously added in be88f3e9. 
```
[x] Bugfix
[ ] Feature
```
Problem was that this changes did not affect the call of clearCache when cacheTimeout emits. To cover this, and give a future-proof solution to affect the way on how clearCache interacts with the store a property has been added to paginator config.
Further, to not break existing implementations and, as most important, to keep the option to negate the …
=> [Paginator-Plugin] Add a config property for not clear the original store when clearCache is called or cacheTimeout emits

akita/src/plugins/paginator/paginatorPlugin.ts
```
[x] Bugfix
[ ] Feature
```
1. Use server-side pagination + filters (10 rows / page)
2. Go to any(not 1) page
3. Apply filter, which filtered dataset to 5 rows at all
4. Get an error:
> Cannot read property 'ids' of undefined
>     at MapSubscriber.project (datorama-akita.js:4455).
Method getPage now takes page from server response, and we don't have errors.
```
[ ] Yes
[x] No
```
I tried to write tests, but have problem with it. I cannot verify filter switching …
=> fix(paginator): take current page from response

cli/plopfile.js, cli/templates/angular/entity-service.tpl, cli/templates/angular/service.tpl
This change to the template fixes error in the generate file because "set" method is only present in EntityStore, not in regular Store.
```
[x ] Bugfix
[ ] Feature
```
Service generated by the CLI uses the wrong method to insert in the store. The "set" method is not present in regular Store, only in EntityStore.
Use "update" method to set the value of the store.
```
[ ] Yes
[x ] No
```
=> Fix generated service for regular Store in CLI

akita/__tests__/upsert.spec.ts, akita/src/entityStore.ts
_Sorry, didn't find a place to update the docs_
```
[ ] Bugfix
[x] Feature
```
Issue Number: #248 
`EntityStore.upsertMany()` now calls a new hook `akitaPreCheckEntity` prior to checking if the store already has the entity.
```
[ ] Yes
[x] No
```
=> feat(upsert-many): add akitaPreCheckEntity hook

schematics/src/ng-g/service/files/__name@dasherize__.service.ts
Added generic type to HttpClient get() method and semicolon to fix initial entity service generation.
Initial:
Fixed:
```
[x] Bugfix
[ ] Feature
```
Typescript errors on initial feature generation
Semicolon and generic type added.
```
[ ] Yes
[x] No
```
=> Fixed Typescript errors when generating feature

akita/src/devtools.ts
_u just need add this information in gitbook if u accept this PR_
```
[ ] Bugfix
[x] Feature ?
```
I think its feature but i'm not 100% sure 😔
Now if we have multiple projects with Akita, in devtools we see many 'Akita' instances to choose and debug. This is a bit annoying and confusing.
Now u can change instance name in `akitaDevTools`. With angular looks like this:
`environment.production ? [] : AkitaNgDevtools.forRoot({
name: 'Custom instance name' …
=> Allow to change instance name visible in devtools

akita/__tests__/queryEntity.spec.ts, akita/src/mapSkipUndefined.ts, akita/src/queryEntity.ts
SelectMany no longer uses observables for each entity, but listens to store changes directly.
Not necessary
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #286 
`selectMany` now directly listens to changes of the state. By using `distinctUntilArrayChanged()`, it is still possible to only emit new values if the array content really changes. This way, we don't have to use `auditTime(0)`, which makes it behave like the other select methods.
```
[ ] Yes
[x] No
```
=> refactor: queryEntity selectMany

akita/src/queryEntity.ts
```
[x] Bugfix
[ ] Feature
```
The typing of `selectEntityAction` currently does not use the generic `IDType` parameter.
The typing of `selectEntityAction` now uses the generic `IDType` parameter for all the overloads.
```
[ ] Yes
[x] No
```
=> fix(entity-query): selectEntityAction typing

akita/src/persistState.ts
Allow `persistState` in non-browser environments.
```
[x] Bugfix
[ ] Feature
```
`persistState` currently cannot be called outside of a browser environment.
Added the `enableInNonBrowser` option which defaults to `false` to optionally allow `persistState` to run outside of a browser environment.
```
[ ] Yes
[x] No
```
=> fix(persist-state): Allow in non-browser

akita/src/root.ts
```
[x] Bugfix
[ ] Feature
```
The `isNativeScript` is incorrect since it check for the property __runtimeVersion of the result of `typeof`. The `typeof` shouldn't be there.
The `isNativeScript` constant is now correct and it's removed from the `isNotBrowser` check. However, now `isNativeScript` isn't used anywhere. Maybe we can simply remove the constant? This could however be a breaking change for people importing the constant; this seems unlikely …
=> fix(root): fix isNotBrowser check

akita/src/transaction.ts
Previously the type of the provided value when using `withTransaction` would be any. Now its using the same pattern as rxjs library to ensure proper typing.
Typing support for `withTransaction`
```
[x] Bugfix
[ ] Feature
```
The type of the value provided when using `withTransaction` was `any`.
The type of the value provided when using `withTransaction` is now the same as the type of the input Observable.
```
[ ] Yes
[x] No
```
=> fix(with-transaction): improve typings

akita/src/entityStore.ts
```
[ ] Bugfix
[x] Feature
```
The type of the entry argument of the function akitaPreUpdateEntity () must be the same as the type of the store.
The type of return must be the same as that of the store
The entry argument type of the function akitaPreUpdateEntity () is free but the return type must always be the same as the type of the store.
```
[ ] Yes
[x] No
```
=> feat(context): release the entry type of akitaPreUpdateEntity

angular/playground/projects/ng-forms-manager/src/lib/forms-manager-options.ts, angular/playground/projects/ng-forms-manager/src/lib/forms-manager.ts, angular/playground/projects/ng-forms-manager/src/public-api.ts
```
[x] Bugfix
[ ] Feature
```
https://github.com/datorama/akita/issues/343
Issue Number: 343
Store gets updated when calling `formManger.unsubscribe()`
```
[ ] Yes
[x] No
```
=> fix(formsmanager.unsubscribe): update store before unsubscribing

akita/__tests__/resetStores.spec.ts, akita/src/store.ts
```
[x] Bugfix
[ ] Feature
```
Currently, if the user provides `resettable: false` in the StoreConfig decorator but it it is set globally in `akitaConfig` with `resettable: true`, the store will be reset.
This is caused due to `resettable` getter returning `undefined` when `options.resettable` was not provided.
`get resettable()` will always return a boolean thus preferring the decorator config over the global
```
[ ] Yes
[x] No
```
=> fix(store): fix resettable getter condition to return boolean

akita/src/store.ts
```
[x] Bugfix
[ ] Feature
```
`resettable` always returning false, therefore global config is never checked
Issue Number: 359
check if config has `resettable` defined first, otherwise return it from options without boolean coercion
```
[ ] Yes
[x] No
```
=> fix(store): fix resettable to not return always false, closes #359

akita/__tests__/queryEntity.spec.ts, akita/src/queryEntity.ts
```
[ ] Bugfix
[x] Feature
```
Currently, `hasActive` does not support single `ActiveState` 
`hasActive` will now also check single active id
```
[ ] Yes
[x] No
```
=> feat(query-entity): support single active state

akita/__tests__/stateHistory.spec.ts, akita/src/plugins/stateHistory/stateHistoryPlugin.ts
Jump to past and jump to future were dropping the present state
```
[x] Bugfix
[ ] Feature
```
When calling jumpToPast(n) for the history plugin, the present state was not added to the "future". Similarly, when calling jumpToFuture(n), the present wasn't added to the past.
The present is not lost when navigating back and forth.
```
[ ] Yes
[x] No
```
[Discussion in medium](https://medium.com/@georgebark/netanel-basal-first-of-all-great-work-loving-akita-b88b905101d1)
=> fix(state-history): fix jump past and future

akita/__tests__/persistForm.spec.ts, akita/src/setValueByString.ts
```
[x] Bugfix
[ ] Feature
```
The PersistNgFormPlugin links the state and form together and updates the state using the value from the valueChanges event. That event emits the value excluding disabled control's values. Everything works fine for the flat state, but if I use tree state and set factoryFnOrPath parameter as 'stepTwo.form' then related state branch will be completely overridden using value excluding values from disabled controls. So the state's shape is …
=> fix: 🐛 persist form should merge the state

akita/src/persistState.ts, akita/src/root.ts
```
[x] Bugfix
[ ] Feature
```
Receiving security errors in multiple browsers when some users goes into incognito mode or have cookies and site data blocked.
For example:
Chrome Mobile: ```SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.```
Mobile Safari: ```SecurityError: The operation is insecure.```
You can see the error yourself in Chrome by blocking cookie and site data: …
=> fix(persist-state): localStorage security errors

angular/playground/package.json, angular/playground/projects/ng-entity-service/karma.conf.js, angular/playground/projects/ng-entity-service/src/lib/ng-entity-service.spec.ts, angular/playground/projects/ng-entity-service/src/lib/ng-entity.service.ts, angular/playground/projects/ng-entity-service/src/lib/setup.ts, angular/playground/projects/ng-entity-service/src/lib/types.ts, angular/playground/projects/ng-entity-service/tsconfig.spec.json
Also refactored to make the code more robust
- Unable to find where the docs are located
```
[ ] Bugfix
[x] Feature
```
Issue Number: #319
The HttpConfig config parameter now accepts a skip flag that skips store writes.
```ts
/**
* Disables writing to the store
*
* You then have to manually write to the store.
* This is useful when pairing the NgEntityService with the PaginatorPlugin
*/
skip?: boolean;
```
```
[ ] Yes
[x] No
```
=> feat(entity-service): added skip flag to skip store writes

akita/src/persistState.ts
```
[x] Bugfix
[ ] Feature
```
This is a continuation of PR https://github.com/datorama/akita/pull/384
If no custom storage is provided to the ```persistState()``` function and the users browser does not allow localStorage then error ```Cannot read property 'getItem' of null``` is thrown.
Don't make calls to storage if it  is not defined.
```
[ ] Yes
[x] No
```
=> fix(persist-state): ignore storage if not defined

akita/__tests__/arrayRemove.spec.ts, akita/src/types.ts
```
[ ] Bugfix
[x] Feature
```
I cannot removing an item of collection by index in easy way, i developed a way to do that by my own:
```
propertyArrayRemoveByIndex(prop: string, index: number): void {
let iterable = -1;
this.store.update(state => ({
[prop]: arrayRemove(state[prop], () => {
iterable++;
if (iterable === index) {
return true;
}
})
}));
}
```
but in your code i found a way to make easier that process
Basically you can remove an item or items of a …
=> feat(array-utils): added index param on ItemPredicate

libs/akita/src/lib/cacheable.ts
return an actual type from 'cacheable' instead of 'Observable<any>'
fix #407
```
[ ] Bugfix
[x] Feature
```
Issue Number: #407 
Now the return type is defined correctly.
```
[ ] Yes
[x] No
```
=> feature(cacheable): change return type

.gitattributes, .vscode/extensions.json, .vscode/settings.json
git now checkout and commits LF
github displays json diffs properly
vscode recommends eslint as eslint is used in the libs
```
[ ] Yes
[x] No
```
=> chore(vscode): git and vscode settings

libs/akita-ng-router-store/src/lib/router.service.ts, libs/akita-ng-router-store/src/lib/router.spec.ts
Fixes the router store not being updated on navigations that don't trigger resolvers.
Closes #398
```
[X] Bugfix
[X] Feature
```
Issue Number: 398
```
[ ] Yes
[X] No
```
I investigated pulling in the current version of ngxs router but this approach was simpler.
I tested that this works properly for my use case. Would you like me to set up unit tests for akita-ng-router-store as part of this PR?
=> feat(router): Fire navigation action on completion

libs/akita/src/__tests__/devtools.spec.ts, libs/akita/src/__tests__/setup.ts, libs/akita/src/lib/actions.ts, libs/akita/src/lib/devtools.ts, libs/akita/src/lib/dispatchers.ts, libs/akita/src/lib/store.ts
A store update triggers query subscribers before releasing the current log action through `resetCustomAction()`:  So if a query subscriber itself triggers a `logAction()` after a previous one (which is still blocking/holding the log action), the previous will be logged again. This is caused by RxJS which is executing all subscribers synchronously and thus the `resetCustomAction()` is executed after `next()` has finished in `dispatch()` (and therefore after the query subscribers). 
Issue Number: #396
The store `BehaviourSubject` itself holds beside the current state the associated log action and sends it to the Redux DevTools before query subscribers are called.
=> fix(devtools): fix multiple logging of same actions

docs/docs/transactions.mdx
There's a line break in the `GenresQuery` word:
There's no line break in `GenresQuery` anymore.
=> docs: remove line break in GenresQuery

libs/akita/src/lib/index.ts
you couldn't import the function `getStoreByName` also the `getEntityStoreByName`
now you can import the function `getStoreByName` also the `getEntityStoreByName`
=> fix(akita): added getStoreByName to index.ts

libs/akita-schematics/src/ng-g/entity-store/files/__name@dasherize__.store.ts, libs/akita-schematics/src/ng-g/entity-store/index.ts, libs/akita-schematics/src/ng-g/entity-store/models/active-state.enum.ts, libs/akita-schematics/src/ng-g/entity-store/models/entity-store-options.model.ts, libs/akita-schematics/src/ng-g/entity-store/schema.json, libs/akita-schematics/src/ng-g/feature/index.ts, libs/akita-schematics/src/ng-g/feature/schema.json
- [] Tests for the changes have been added (for bug fixes / features)
- [] Docs have been added / updated (for bug fixes / features)
In the current behavior, you can't generate an entity store with MultiActive implementation using Schematics.
Issue Number: [#468](https://github.com/datorama/akita/issues/468)
From now on you can pass to the flag withActive a value - "Active" | "MultiActive" and it will generate the desired state.
=> feature(schematics): adding the option the create MultiActive entity store

docs/docs/additional/optimstic-updates.mdx, libs/akita/src/__tests__/queryEntity.spec.ts, libs/akita/src/lib/entityStore.ts, libs/akita/src/lib/index.ts, libs/akita/src/lib/trackIdChanges.ts, libs/akita/src/lib/types.ts, libs/akita/src/lib/updateEntities.ts
Add rxjs operator to track entity id updates and automatically re-evaluate the query.
=> feat(entity-store): track entity id updates

docs/docs/best-practices.mdx
Link to `Array Utils` is pointing to url that doesn't exist
https://datorama.github.io/akita/docs/best-practices/additional/array
New link points to correct url
https://datorama.github.io/akita/docs/additional/array/
=> docs: fix broken link to array utils

docs/docs/best-practices.mdx
The Best Practices page had a broken link to the Array Utils page
https://datorama.github.io/akita/docs/best-practices has a bad link to the Array Utils page. It is linking to https://datorama.github.io/akita/additional/array instead of https://datorama.github.io/akita/docs/additional/array
Fixes the broken link
=> docs: fix broken array utils link

docs/docs/config.mdx
Relative links in page https://datorama.github.io/akita/docs/config/ don't work: `[EntityId](entities/entity-store#entity-id) `=> 
Result: https://datorama.github.io/akita/docs/config/entities/entity-store#entity-id
Expected result: https://datorama.github.io/akita/docs/entities/entity-store/#entity-id
=> docs: Update relative links

libs/akita-ng-router-store/src/lib/router.service.ts
I don't know what provokes `router.getCurrentNavigation().extras` to be undefined.
Trying the obvious by navigating the router with undefined as the extras parameter still doesn't return undefined. `await ngZone.run(() => router.navigate(['/test/undefined'], undefined));`
So unless someone figures out the cause of the issue, I don't think a test makes sense.
I don't think there's anything to document here.
Issue Number: #399 
SerializeRouter now returns an empty object for 'navigationExtras' should the `router.getCurrentNavigation().extras.state` be unavailable (undefined) for any reason.
I cannot test the locally compiled library due to some weird rxjs dependency errors. I did test …
=> fix(router-store): serializeRoute 'state' undefined

docs/docs/config.mdx
Fix links to cache and entity id. Add .mdx to file name so the links also work when editing in Github.
"Caching Support" and "EntityId" links do not work
The links now link to the correct pages.
=> Fix links in config.mdx

docs/docs/plugins/pagination.mdx
In one exemple, the code try to get ata from this.pagninator. But this paginator field does not exist. It was paginatorRef.
- [x ] Docs have been added / updated (for bug fixes / features)
- [x ] Documentation content changes
=> docs(PaginationPlugins) update exemple pagination.mdx

docs/docs/best-practices.mdx
Link to "Array Utils" in [best practices](https://datorama.github.io/akita/docs/best-practices/#the-query) links to 404 page: https://datorama.github.io/akita/docs/best-practices/additional/array
Fix link to point to https://datorama.github.io/akita/docs/additional/array
This works in a similar instance: [config.mdx](https://github.com/datorama/akita/blob/ea131a5/docs/docs/config.mdx) links to `additional/` pages in https://datorama.github.io/akita/docs/config/
=> docs: Fix link

docs/docs/enhancers/devtools.mdx
https://datorama.github.io/akita/docs/enhancers/devtools/
404: https://datorama.github.io/akita/docs/img/devtools.gif
Use [`useBaseUrl`](https://v2.docusaurus.io/docs/static-assets/) to fetch image
`yarn start`
=> docs(devtools): fix broken image

docs/docs/ui.mdx
Fixes a type error that'd come up when functions initialize properties in the constructor.
Note the _definite assignment assertion modifiers_ (introduction in [TypeScript 2.7](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html#strict-class-initialization))
=> docs(ui): definite assignment assertion modifiers for initial state

libs/akita-schematics/src/ng-g/utils/workspace.ts
- [ X ] The commit message follows our guidelines: https://github.com/datorama/akita/blob/master/CONTRIBUTING.md#commit
- [ ? ] Tests for the changes have been added (for bug fixes / features)
- [ ? ] Docs have been added / updated (for bug fixes / features)
- [ X ] Refactoring (no functional changes, no api changes)
When using the `@datorama/akita` schematics with the `nx` command it fails as it's only looking for `angular.json`.
NX Monorepo `workspace.json` is the same format for the requirements of running a schematic, this adds support to run the schematics using the `nx` command.
e.g.
`nx g @datorama/akita:af core-state --plain --project=core-api`
- [ X ] No
=> refactor(schematics): Add support for nx workspace.json

docs/docs/angular/effects.mdx
updating code snippet to reflect pluralized import module name
When copying the code snippet I see ```../../node_modules/@datorama/akita-ng-effects/datorama-akita-ng-effects"' has no exported member named 'AkitaNgEffectModule'. Did you mean 'AkitaNgEffectsModule'?``` inside of angular project.
Correctly imports the declared module.
=> docs: pluralize effects module import code snippet

docs/docs/plugins/dirty-check.mdx, libs/akita/src/__tests__/dirtyCheck.spec.ts, libs/akita/src/lib/plugins/dirtyCheck/dirtyCheckPlugin.ts
DirtyCheck getHead() is protected.
Issue Number: #593 
DirtyCheck getHead() is now public.
Other changed were introduced by Prettier. Fixed some small linting issues too.
=> feat: make DirtyCheck's getHead() public

docs/docs/additional/cache.mdx
Syntax error in cachable code example
No syntax error in cachable code example
=> docs(cache): fix cacheable example

libs/akita/src/__tests__/stateHistory.spec.ts, libs/akita/src/lib/entityStore.ts, libs/akita/src/lib/plugins/plugin.ts, libs/akita/src/lib/plugins/stateHistory/stateHistoryPlugin.ts, libs/akita/src/lib/setValueByString.ts
instead of updating state we should be replacing it
✅ Closes: #619
On undo/redo a store is being updated (merged), not replaced.
Issue Number: #619 
On undo/redo a store is being replaced.
I had to update the `EntityStore`'s `replace` method because of getting an error, something like:
> Cannot assign to 'id' because it is a read-only property
=> fix: 🐛 change the update method in the StateHistoryPlugin

docs/docs/additional/operators.mdx, libs/akita-ng-router-store/src/lib/router.query.ts, libs/akita/src/lib/filterNil.ts, libs/akita/src/lib/index.ts, libs/akita/src/lib/plugins/plugin.ts, libs/akita/src/lib/types.ts
Closes #606
In strict mode, filterNil fails to remove undefined from the input type.
Issue Number: 606
filterNil correctly removes undefined from the input type.
=> fix: filterNil removes undefined from resulting types in strict mode

docs/docs/angular/entity-service.mdx, libs/akita-ng-entity-service/src/lib/ng-entity-service.config.ts, libs/akita-ng-entity-service/src/lib/ng-entity-service.loader.ts, libs/akita-ng-entity-service/src/lib/ng-entity-service.spec.ts
Added Configuration to enable NgEntityServiceLoader to utilize a ReplaySubject
fixes #668
Issue Number: #668
An option to use a `ReplaySubject` over a `Subject` for the `NgEntityServiceLoader` dispatcher. This allows late subscribers (e.g. components that call `get()` via `ngOnInit` and subscribe to `get$` via async pipe in the template) to receive the latest emission on subscription.
=> fix(akita-ng-entity-service): loader late subscriber

apps/angular-store-app/src/app/cart/state/cart.query.ts, apps/angular-store-app/src/app/contacts/contacts-page/contacts-page.component.ts, apps/angular-store-app/src/app/products/products.component.ts, apps/angular-store-app/src/app/todos-app/state/todos.query.ts, docs/docs/angular/architecture.mdx, docs/docs/plugins/pagination.mdx, libs/akita-ng-effects/README.md, libs/akita/src/__tests__/pagination.spec.ts, libs/akita/src/lib/plugins/dirtyCheck/dirtyCheckPlugin.ts
When I was looking at the docs I noticed that there are some deprecated usages of `combineLatest` like this:
When I was replacing it in `.mdx` files, I noticed that there were some in `.ts` file too, so I went ahead and changed all usages from `combineLatest(...)` to `combineLatest([...])`.
- There are some failing tests in `libs/akita/src/__tests__/pagination.spec.ts` and `libs/akita/src/__tests__/persistState.spec.ts`;
- It seems like `eslint` and `Prettier` aren't happy with the current codebase. To make this commit, I had to skip it by using `--no-verify`, otherwise many changes would be applied. It would be good to create a separate PR to run it through the …
=> refactor: replace `combineLatest` deprecated usages

libs/akita-ng-effects/package.json, libs/akita/package.json
Correcting the homepage links in package.json's
When on the page for [`@dataorama/akita`](https://www.npmjs.com/package/@datorama/akita) or [`@dataorama/akita-ng-effects`](https://www.npmjs.com/package/@datorama/akita-ng-effects) on npm and you click the "Homepage" link, it takes to a 404 not found as the link is missing the repository name. i.e. instead of github.com/datorama/akita/tree, it is github.com/dataorama/tree
Clicking the homepage links will take to the correct repository
=> fix: 🐛 correcting homepage links in package.json's

libs/akita-ng-effects/src/__tests__/module-manager.service.spec.ts, libs/akita-ng-effects/src/lib/module-manager.service.ts
akita-ng-effects: Had a situation where AngularFireAuth was a object of a custom Proxy type that when property.isEffect was called, it returned an object which evaluated as truthy passing the if statement before blowing up.
When isEffect was called on a property that does not return undefined and instead returns something non boolean but truthy the if statement passes incorrectly. 
```
property.isEffect // in my case the call resolves to Proxy { length: 0, name: '' } which is truthy and passes the check
```
```
if (property.isEffect) {
// blows up in here because it's not an effect.
});
```
changing to an explicit check for boolean true fixes the problem
```
if …
```
=> fix: Explicit check for boolean value

docs/docs/additional/middleware.mdx, packages/akita/src/__tests__/storeMiddleware.spec.ts, packages/akita/src/lib/entityStore.ts
```
[ ] Bugfix
[x] Feature
[z] Documentation content changes
```
currently there isn't any ability to use `this` in middleware hooks without doing a "binding trick" 
Issue Number: #782 
It adds `bind` to the entityStore middleware hooks
```
[ ] Yes
[x] No
```
=> feat(akita): 🔥 add native middleware hooks binding support

packages/akita-schematics/src/ng-g/utils/pluralize.ts, packages/akita-schematics/src/ng-g/utils/project.ts, packages/akita-schematics/src/ng-g/utils/string.ts, packages/akita-schematics/src/schematics-core/utility/project.ts, packages/akita-schematics/src/schematics-core/utility/strings.ts
```
[ ] Bugfix
[ ] Feature
```
[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.
No change, …
=> refactor: replace deprecated String.prototype.substr()

packages/ng-playground/src/app/cart/cart.component.ts, packages/ng-playground/src/app/cart/state/cart.query.ts, packages/ng-playground/src/app/cart/state/cart.store.ts, packages/ng-playground/src/app/nav/nav.component.ts
* Remove `FormsManager` navbar link since it was deprecated in salesforce/akita@45a9d112
* Add missing `remove` from cart method and remove notification part as a result of deprecating previous effects-based implementation salesforce/akita@2aaf7e351
```
[ ] Yes
[x] No
```
While working on another PR I found that the demo app is broken. This PR fixes it.
=> chore(demo): fix logical issues in demo app

nx.json, packages/akita/src/lib/entityStore.ts, packages/akita/src/lib/plugins/dirtyCheck/dirtyCheckPlugin.ts, packages/akita/src/lib/plugins/plugin.ts, packages/akita/src/lib/plugins/stateHistory/stateHistoryPlugin.ts, packages/akita/src/lib/queryEntity.ts, packages/akita/src/lib/runStoreAction.ts
This PR makes the public API of Akita to be consumable in a strict typescript project (and without skipLibCheck).
Refs: salesforce/akita#870
----
The first thing I've tried is to enable `strict: true` for this monorepo and fix them - but the amount of errors in such case is pretty significant 🥵
After that, I tried to fix only TS errors that I found while consuming akita@8.0.0 in my project. And such approach helped me to decrease the API surface to a couple of places, which was somehow fixed in this draft/spike #1050. 
Interestingly, #1050 already allowed me to consume akita in Angular 15 project with a strict mode (and without skipLibCheck).
But unfortunately:
~~1. I'm not confident in these TS-related changes (don't have a big project to test on)~~
**UPD: @qnku @nunoarruda confirmed …
=> fix(akita): support TS strict mode

packages/akita/jest.config.ts, packages/akita/tsconfig.lib.json, packages/akita/tsconfig.spec.json
```
[x] Bugfix
```
Currently, akita is bundled with its tests so npm package contains them too https://unpkg.com/browse/@datorama/akita@8.0.0/src/
This change excludes `src/__tests__` from tsc compilation so there is less compiled code in a dist
Also includes other minor changes that were replicated from a newly generated lib
```
[ ] Yes
[x] No
```
=> fix(akita): exclude tests from npm package

packages/akita/src/__tests__/env.spec.ts
```
```
The issue can be experienced only when switching your tsconfig.base paths to use `dist` instead of `src` (that is what I have tried to do in this repo while working on #1050), because in such case `jest` will not be able to import it (so this test fails)
Using relative paths within the same project prevents circular self-dependency
```
[ ] Yes
[x] No
```
=> refactor(general): use relative import
